data_split:
  split_date: "2024-10-01T00:00:00Z"

target_creation:
  method: "triple_barrier"
  pt_multiplier: 2.0
  sl_multiplier: 1.5
  time_horizon: 24
  min_ret: 0.0005

training:
  asset_symbol: "XAUUSD"
  timeframe: "H1"
  model_type: "lightgbm"

model_params:
  lightgbm:
    objective: binary
    metric: auc
    is_unbalance: true
    n_estimators: 1000
    learning_rate: 0.01
    max_depth: 4  # زدنا العمق قليلاً لاستيعاب التفاعلات بين RSI و Vol
    num_leaves: 31
    n_jobs: 1 # لتفادي مشاكل ويندوز